### ISSUE TITLE
sentiment analysis is not working

### ISSUE THREAD

**Issue by thdotnet** [Microsoft/Cognitive-TextAnalytics-DotNet#10]
I've did a test using the following code and the response has 0 documents and of course, don't have the sentiment. 

```
using System;
using Microsoft.ProjectOxford.Text.Core;
using Microsoft.ProjectOxford.Text.Sentiment;
using Microsoft.ProjectOxford.Text;

namespace ExemploAnaliseDeTexto
{
    class Program
    {
        static void Main(string[] args)
        {
            SentimentDocument document = new SentimentDocument
            {
                Id = "1",
                Language = "en",
                Text = "I don't like when examples don't work."
            };

            SentimentRequest request = new SentimentRequest();
            request.Documents.Add(document);

            SentimentClient client = new SentimentClient("{my-api-key-here}");
            var response = client.GetSentiment(request);

            Console.Read();
        }
    }
}

```

**Comment by thdotnet** [comment]
I am using Dotnet Core 2.1 should be this the reason? I've found a package Microsoft.ProjectOxford.Text.DotNetCore but due the small number of downloads, I am not sure if I should use that one. Also, did a test with that, it's returning 401 even tough I am using the right key.

**Comment by nrobert** [comment]
You should use newer package which is `Microsoft.Azure.CognitiveServices.Language.TextAnalytics`, see here: https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.TextAnalytics/2.8.0-preview
There is a `SentimentAsync` method.
But the package is still in preview.

Sources are here: https://github.com/Azure/azure-sdk-for-net/tree/master/src/SDKs/CognitiveServices/dataPlane/Language/TextAnalytics
